# 本程序及代码在人工智能工具辅助下完成：OpenAI Codex（GPT-5，OpenAI；GPT-5 发布于 2025-08-07）。
"""Generate the paper's numerical LaTeX tables from archived, verified results.

Run from any directory: python code/generate_paper_tables.py
The generated files live in paper/tables/ and are included by paper/main.tex.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
TABLES = ROOT / "paper" / "tables"


def load(name: str) -> dict:
    return json.loads((RESULTS / f"{name}.json").read_text(encoding="utf-8"))


def write(name: str, content: str) -> None:
    TABLES.mkdir(exist_ok=True)
    (TABLES / f"{name}.tex").write_text(
        "% Generated by code/generate_paper_tables.py; edit the source results, then regenerate.\n"
        + content.rstrip() + "\n",
        encoding="utf-8",
    )


def table(caption: str, label: str, columns: str, header: str, rows: list[str],
          size: str = r"\small", resize: bool = False) -> str:
    body = (r"\begin{tabular}{" + columns + "}\n" + r"\toprule" + "\n"
            + header + r"\\\midrule" + "\n" + "\n".join(row + r"\\" for row in rows)
            + "\n" + r"\bottomrule\end{tabular}")
    # The 2026 contest rule specifies 12 pt Songti for all other Chinese text,
    # with no table exception. Keep the legacy call parameters for provenance,
    # but never reduce or scale table text in the current paper.
    return (r"\begin{table}[H]\centering\normalsize" + "\n"
            + r"\caption{" + caption + r"}\label{tab:" + label + "}\n"
            + body + "\n" + r"\end{table}")


def minutes(seconds: float) -> str:
    return f"{seconds / 60:.2f}"


def zone(number: int) -> str:
    return f"S{number:03d}"


def main() -> None:
    profile = load("data_profile")
    q1, q2, q3, q4 = (load(n) for n in ("q1_rho20", "q2", "q3", "q4"))
    boxes = profile["boxes"]
    assert len(boxes) == q2["summary"]["delivered"] == q3["summary"]["delivered"]
    assert len(q1["routes"]) == q1["summary"]["count"]
    assert len(q2["routes"]) == q2["summary"]["count"]
    assert len(q3["communication"]) == q3["summary"]["comm_intervals"]

    # Formal Q2 protocol: four methods, ten matched independent starts, and a
    # fixed valid-candidate budget.  Keep this separate from earlier scans.
    q2_formal = load("q2_formal_protocol")
    formal_rows = []
    method_cn = {"grasp": "随机化构造", "hill": "局部爬山",
                 "anneal": "模拟退火", "tabu": "禁忌搜索"}
    for method in q2_formal["protocol"]["methods"]:
        stat = q2_formal["algorithm_statistics"][method]
        formal_rows.append(
            f"{method_cn[method]} & {stat['feasible_runs']}/{stat['runs']} & "
            f"{stat['makespan']['mean']/60:.2f}$\\pm${stat['makespan']['std']/60:.2f} & "
            f"{stat['energy']['mean']:.4f}$\\pm${stat['energy']['std']:.4f} & "
            f"{stat['count']['mean']:.2f}$\\pm${stat['count']['std']:.2f}"
        )
    write("q2_formal_protocol", table(
        "同初始解下四种路线搜索的性能比较（均值±标准差，每法10个种子）",
        "q2_formal_protocol", "lrrrr",
        "方法 & 可行运行 & 返航/min & 能耗/kWh & 架次",
        formal_rows))

    # The 15-by-3 capacities and the actual Q1 batch allocation share one table.
    q1_rows = []
    for node in range(1, 16):
        caps = {g: next(x["maxload"] for x in q1["capacities"]
                        if x["node"] == node and x["g"] == g) for g in "ABC"}
        trips = [r for r in q1["routes"] if r["order"] == [node]]
        q1_rows.append(
            f"{zone(node)} & {caps['A']:.2f} & {caps['B']:.2f} & {caps['C']:.2f} & "
            f"{sum(len(r['boxes']) for r in trips)} & {len(trips)} & "
            f"{sum(r['energy'] for r in trips):.3f}"
        )
    write("q1_capacity_batches", table(
        r"20\%返航储备下各服务区三机型最大安全载荷与单点组批",
        "q1_capacity_batches", "lrrrrrr",
        r"服务区 & A/kg & B/kg & C/kg & 箱数 & 架次 & 能耗/kWh", q1_rows,
        r"\small"))

    # Service-area delivery and hard-deadline slack are calculated box by box.
    q2_delivery = {int(index): route["start"] + time for route in q2["routes"]
                   for index, time in route["deliver"].items()}
    assert len(q2_delivery) == len(boxes)
    assert abs(max(q2_delivery.values()) - q2["summary"]["last_delivery"]) < 1e-6
    service_rows = []
    for node in range(1, 16):
        indices = [i for i, box in enumerate(boxes) if box["node"] == node]
        hard = [i for i in indices if boxes[i]["medical"] or boxes[i]["first"]]
        def deadline(i: int) -> float:
            box = boxes[i]
            return min(box["due"] if box["medical"] else float("inf"),
                       box["first_deadline"] if box["first"] else float("inf"))
        slack = min((deadline(i) - q2_delivery[i] for i in hard), default=None)
        service_rows.append(
            f"{zone(node)} & {len(indices)} & {sum(boxes[i]['w'] for i in indices)} & "
            f"{minutes(max(q2_delivery[i] for i in indices))} & {len(hard)} & "
            + (f"{slack:.2f}" if slack is not None else "---")
        )
    write("q2_service_delivery", table(
        "问题二各服务区交付完成情况与最紧硬截止余量",
        "q2_service_delivery", "lrrrrr",
        r"服务区 & 箱数 & 质量/kg & 最后交付/min & 硬时限箱 & 最小提前/s",
        service_rows, r"\small"))

    # Complete Q2 trip list belongs in the appendix; the submission workbook
    # retains per-box delivery times and the full route witness.
    flight_route_rows = []
    flight_metric_rows = []
    for route in q2["routes"]:
        stops = ",".join(zone(n) for n in route["order"])
        flight_route_rows.append(
            f"{route['id']} & {route['unit']} & {route['battery']} & {stops} & {len(route['boxes'])}"
        )
        flight_metric_rows.append(
            f"{route['id']} & {minutes(route['start'])} & {minutes(route['end'])} & "
            f"{route['energy']:.3f} & {100 * route['soc']:.2f}"
        )
    write("q2_flights", table(
        "问题二入选方案全部24个运输架次：任务与资源",
        "q2_flights", "llllr",
        r"架次 & 机体 & 电池 & 服务区顺序 & 箱数", flight_route_rows)
        + "\n" + table(
        "问题二入选方案全部24个运输架次：时间与能源（续）",
        "q2_flight_metrics", "lrrrr",
        r"架次 & 开始/min & 返航/min & 能耗/kWh & 返航SOC/\%",
        flight_metric_rows))

    relay_site_rows = []
    relay_metric_rows = []
    for relay in q3["relays"]:
        lon, lat, alt = relay["pos"]
        relay_site_rows.append(
            f"{relay['id']} & {relay['site']} & {relay['unit']}/{relay['component']} & "
            f"{lon:.4f}, {lat:.4f} & {alt:.1f}"
        )
        relay_metric_rows.append(
            f"{relay['id']} & {minutes(relay['ready'])} & {minutes(relay['service_end'])} & "
            f"{minutes(relay['end'])} & {relay['energy']:.3f} & {100 * relay['soc']:.2f}"
        )
    write("q3_relay_tasks", table(
        "问题三三班中继任务的悬停位置与资源",
        "q3_relay_tasks", "lcllr",
        r"任务 & 点 & 机体/组件 & 经纬度 & 海拔/m", relay_site_rows)
        + "\n" + table(
        "问题三三班中继任务的时窗与能源（续）",
        "q3_relay_metrics", "lrrrrr",
        r"任务 & 建链/min & 服务结束/min & 返航/min & 能耗/kWh & 返航SOC/\%",
        relay_metric_rows))

    providers = Counter(x["provider"] for x in q3["communication"])
    comm_rows = []
    for provider, meaning in (("G01", "固定网关直连"), ("R01", "经西部中继机"),
                              ("R02", "经东部或北部中继机")):
        values = [x["margin"] for x in q3["communication"] if x["provider"] == provider]
        comm_rows.append(f"{provider} & {meaning} & {providers[provider]} & {min(values):.5f}")
    comm_rows.append(f"合计 & 连续通信证书 & {len(q3['communication'])} & "
                     f"{q3['summary']['comm_min_margin']:.5f}")
    write("q3_communication", table(
        "问题三连续通信区间证书按连接方式汇总",
        "q3_communication", "llrr",
        r"连接方式 & 对应链路 & 已验证区间数 & 最小证明裕量/dB",
        comm_rows))

    q3_audit = load("q3_formal_coordination_audit")
    audit_rows = []
    for row in q3_audit["coordination_rounds"]:
        audit_rows.append(
            f"{row['round']} & {row['master_transport_family']} & "
            f"{row['communication_candidates']} & {row['certified_candidates']} & "
            f"{row['returned_min_link_margin_db']:.6f}"
        )
    choice = q3_audit["maximin_link_margin_choice"]
    audit_rows.append(
        f"裕度最大候选 & {choice['transport_family']} & 32 & 32 & "
        f"{choice['min_link_margin_db']:.6f}"
    )
    write("q3_coordination_audit", table(
        "有限候选分解协调审计与连续通信裕度",
        "q3_coordination_audit", "llrrr",
        r"轮次/汇总 & 运输族 & 候选数 & 获证数 & 返回裕度/dB",
        audit_rows))

    q2s, q3s = q2["summary"], q3["summary"]
    compare_rows = [
        f"运输架次 & {q2s['count']} & {q3s['count']} & +{q3s['count'] - q2s['count']}",
        f"中继架次 & 0 & {q3s['relay_count']} & +{q3s['relay_count']}",
        f"全部设备返航/min & {minutes(q2s['makespan'])} & {minutes(q3s['makespan'])} & +{minutes(q3s['makespan'] - q2s['makespan'])}",
        f"总能耗/kWh & {q2s['energy']:.4f} & {q3s['energy']:.4f} & +{q3s['energy'] - q2s['energy']:.4f}",
        f"最后一箱交付/min & {minutes(q2s['last_delivery'])} & {minutes(q3s['last_delivery'])} & +{minutes(q3s['last_delivery'] - q2s['last_delivery'])}",
        "普通物资加权迟到/系数$\\cdot$s & 0 & 0 & 0",
    ]
    write("q2_q3_compare", table(
        "问题二运输方案与问题三通信约束下联合方案对比",
        "q2_q3_compare", "lrrr",
        r"指标 & 问题二 & 问题三 & 差值", compare_rows, r"\small"))

    group_rows = []
    for k in ("2", "3"):
        for number, group in enumerate(q4["schemes"][k]["selected"]["groups"], 1):
            names = ", ".join(zone(n) for n in sorted(group["nodes"]))
            group_rows.append(
                f"{k}组-{number} & {names} & {group['boxes']} & "
                f"{len(group['transport_ids'])} & {group['work'] / 3600:.2f}"
            )
    write("q4_groups", table(
        "问题四两组和三组分区的服务区、货箱与固定任务工作量",
        "q4_groups", r"l>{\raggedright\arraybackslash}p{8.0cm}rrr",
        r"分组 & 服务区 & 箱数 & 运输架次 & 工作量/h", group_rows, r"\scriptsize"))

    compare4 = []
    vector4 = []
    for k in ("2", "3"):
        selected = q4["schemes"][k]["selected"]
        compare4.append(
            f"{k}组 & {q4['schemes'][k]['evaluated']} & "
            f"{sum(selected['deficit'])} & {sum(selected['total'])} & "
            f"{selected['cv']:.4f} & {sum(selected['unused'])}"
        )
        fmt = lambda values: "(" + ",".join(str(x) for x in values) + ")"
        vector4.append(
            f"{k}组 & {fmt(selected['duplicated'])} & {sum(selected['duplicated'])} & "
            f"{fmt(selected['unused'])} & {sum(selected['unused'])} & "
            f"{fmt(selected['deficit'])} & {sum(selected['deficit'])} & {selected['cv']:.4f}"
        )
    write("q4_compare", table(
        "问题四最小缺口分区的综合比较",
        "q4_compare", "lrrrrr",
        r"方案 & 穷举划分数 & 库存缺口/件 & 配置总数/件 & 工作量变异系数 & 闲置组件/组",
        compare4, r"\scriptsize"))
    write("q4_resource_metrics", table(
        "问题四重复配置、库存闲置与库存缺口的分离核算",
        "q4_resource_metrics", r"l>{\raggedright\arraybackslash}p{2.8cm}r>{\raggedright\arraybackslash}p{2.8cm}r>{\raggedright\arraybackslash}p{2.8cm}rr",
        r"方案 & duplicated向量 & 合计 & unused向量 & 合计 & deficit向量 & 合计 & CV",
        vector4))

    stress = json.loads((RESULTS / "controlled_stress_20260926.json").read_text(encoding="utf-8"))
    energy_rows = []
    for row in stress["transport_energy"]:
        name = "问题二" if row["question"] == "q2" else "问题三运输"
        failed = ",".join(row["violating_routes"]) if row["violating_routes"] else "---"
        energy_rows.append(
            f"{name} & {row['horizontal_multiplier']:.2f} & {row['min_soc']*100:.2f} & "
            f"{row['violation_count']} & {failed}"
        )
    write("energy_multiplier", table(
        "固定运输方案的水平能耗倍率压力检验",
        "energy_multiplier", r"lrrrl",
        r"方案 & 倍率 & 最低SOC/\% & 越界架次 & 越界架次编号",
        energy_rows, r"\scriptsize"))

    link_rows = [f"{row['extra_loss_db']:.1f} & {row['uncertified_intervals']} & "
                 f"{row['minimum_remaining_margin_db']:.3f}"
                 for row in stress["communication_loss"]]
    write("communication_loss", table(
        "固定链路分配下额外损耗对连续证书的影响",
        "communication_loss", "rrr",
        r"额外链路损耗/dB & 未获证区间数 & 最低剩余裕量/dB",
        link_rows, r"\small"))

    scan = json.loads((RESULTS / "kmax_scan_20260926.json").read_text(encoding="utf-8"))
    objective = scan["protocol"]["objective"]
    k_scope_rows = []
    k_metric_rows = []
    for k in scan["protocol"]["k_values"]:
        trials = [t for t in scan["trials"] if t["kmax"] == k]
        passed = [t for t in trials if t["status"] == "PASS"]
        assert len(trials) == 12 and len(passed) == 12
        best = min(passed, key=lambda t: tuple(t["metrics"][field] for field in objective))
        m = best["metrics"]
        assert m["hard_violations"] == 0
        zero_late = sum(t["metrics"]["weighted_tardiness"] == 0 for t in passed)
        used_stops = max(len(r["order"]) for t in passed for r in t["routes"])
        evaluations = sum(t["valid_candidates_evaluated"] for t in passed)
        k_scope_rows.append(
            f"{k} & {len(passed)}/12 & {zero_late}/12 & {used_stops} & {evaluations}"
        )
        k_metric_rows.append(
            f"{k} & {minutes(m['makespan'])} & {m['energy']:.2f} & {m['count']}"
        )
    write("q2_kmax_scan", table(
        "K上限受控扫描：各组12次运行的可行性与搜索规模",
        "q2_kmax_scan", "rrrrr",
        r"$K_{\max}$ & 硬可行 & 零软迟到 & 实际最多站 & 有效候选评估",
        k_scope_rows)
        + "\n" + table(
        "K上限受控扫描：各组字典序最佳见证（续）",
        "q2_kmax_metrics", "rrrr",
        r"$K_{\max}$ & 最后返航/min & 能耗/kWh & 架次",
        k_metric_rows))


if __name__ == "__main__":
    main()
